name: Build for Release

on:
  push:
    branches: [ release/* ]

jobs:
  fat:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build fat jar
      run: sbt assembly
    - name: Upload fat jar
      uses: actions/upload-artifact@v1
      with:
        name: jars
        path: target/scala-2.13/swingtest-assembly-1.0.jar
  osx:
    needs: fat
    runs-on: [macos]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: '14.0.0'
        java-package: jdk
        architecture: x64
    - name: Download fat jar
      uses: actions/download-artifact@v1
      with:
        name: jars
    - name: Package jar as dmg installer
      run: jpackage --name SwingTest -i jars --main-class example.Main --main-jar swingtest-assembly-1.0.jar
    - name: Upload dmg
      uses: actions/upload-artifact@v1
      with:
        name: dmgs
        path: SwingTest-1.0.dmg
  windows:
    needs: fat
    runs-on: [windows-latest]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: '14.0.0'
        java-package: jdk
        architecture: x64
    - name: Download fat jar
      uses: actions/download-artifact@v1
      with:
        name: jars
    - name: Package jar as msi
      run: jpackage --name SwingTest --type msi -i jars --main-class example.Main --main-jar swingtest-assembly-1.0.jar --win-dir-chooser
    - name: View artifacts
      run: dir
    - name: Upload installer
      uses: actions/upload-artifact@v1
      with:
        name: msis
        path: SwingTest-1.0.msi
